version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    networks:
      - elastic
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9200"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 7s

  employee:
    image: employee
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ELASTICSEARCH_URL=http://elasticsearch:9200

    volumes:
      - type: bind
        source: ./docker-setup/config.yml
        target: /usr/share/docker-config/config.yml
        read_only: true
    depends_on:
      - "elasticsearch"
    command: ["./docker-setup/wait-for-it.sh", "-t 20", "elasticsearch:9200"]
    #     condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - elastic



volumes:
  elasticsearch:
    driver: local
networks:
  elastic:
    driver: bridge